package chateeconn
package main

import (
	"context"
	"fmt"
	"net/http"
	"os"
	"os/signal"










































































































}	logger.Info("Server stopped")	}		logger.Error("Server forced to shutdown", log.Error(err))	if err := server.Shutdown(ctx); err != nil {	h.Shutdown()	// Stop hub	defer cancel()	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)	// Graceful shutdown	logger.Info("Shutting down server...")	<-quit	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)	quit := make(chan os.Signal, 1)	// Wait for shutdown signal	}()		}			logger.Fatal("WebSocket server failed", log.Error(err))		if err := server.ListenAndServe(); err != nil && err != http.ErrServerClosed {		logger.Info("WebSocket server started", log.String("addr", server.Addr))	go func() {	// Start server	}		Handler: router,		Addr:    fmt.Sprintf("%s:%d", cfg.HTTP.Host, cfg.HTTP.Port+1), // Use HTTP port + 1 for WS	server := &http.Server{	// Create HTTP server	})		})			"connections": h.ConnectionCount(),			"status":      "ok",		c.JSON(http.StatusOK, gin.H{	router.GET("/health", func(c *gin.Context) {	// Health endpoints	})		connection.HandleWebSocket(c, h, cfg.WebSocket, logger)	router.GET("/ws", func(c *gin.Context) {	// WebSocket endpoint	router.Use(gin.Recovery())	router := gin.New()	}		gin.SetMode(gin.ReleaseMode)	if cfg.IsProd() {	// Setup Gin	go h.Run()	// Start hub	})		PongWait:     cfg.WebSocket.PongWait,		PingInterval: cfg.WebSocket.PingInterval,		Logger:       logger,	h := hub.NewHub(hub.HubConfig{	// Create connection hub	}		logger.Fatal("Failed to init snowflake", log.Error(err))	if err := snowflake.Init(3); err != nil {	// Initialize snowflake ID generator	)		log.String("version", cfg.Service.Version),		log.String("name", cfg.Service.Name),	logger.Info("Starting ChateeConn service",	logger := log.Default()	}		os.Exit(1)		fmt.Fprintf(os.Stderr, "Failed to init logger: %v\n", err)	}); err != nil {		AddCaller: true,		Format:    cfg.Log.Format,		Level:     cfg.Log.Level,	if err := log.Init(log.LogConfig{	// Initialize logger	}		os.Exit(1)		fmt.Fprintf(os.Stderr, "Failed to load config: %v\n", err)	if err != nil {	cfg, err := config.Load("")	// Load configurationfunc main() {)	"chatee/services/chatee-conn/hub"	"chatee/services/chatee-conn/connection"	"chatee/commonlib/snowflake"	"chatee/commonlib/log"	"chatee/commonlib/config"	"github.com/gin-gonic/gin"	"time"	"syscall"