package chateehttp
package main

import (
	"context"















































































































































































































}	}		}			chats.POST("/:id/channels", h.CreateChannel)			chats.GET("/:id/channels", h.ListChannels)			chats.DELETE("/:id/participants/:userId", h.RemoveParticipant)			chats.POST("/:id/participants", h.AddParticipant)			chats.GET("", h.ListChats)			chats.DELETE("/:id", h.DeleteChat)			chats.PUT("/:id", h.UpdateChat)			chats.GET("/:id", h.GetChat)			chats.POST("", h.CreateChat)		{		chats := v1.Group("/chats")		// Group chat routes		}			threads.GET("/:id/replies", h.ListReplies)			threads.POST("/:id/replies", h.CreateReply)			threads.GET("", h.ListThreads)			threads.DELETE("/:id", h.DeleteThread)			threads.PUT("/:id", h.UpdateThread)			threads.GET("/:id", h.GetThread)			threads.POST("", h.CreateThread)		{		threads := v1.Group("/threads")		// Thread routes (topic-based messaging)		}			mcp.POST("/servers/:id/tools/:tool/call", h.CallMCPTool)			mcp.GET("/servers/:id/tools", h.ListMCPTools)			mcp.POST("/servers/:id/disconnect", h.DisconnectMCPServer)			mcp.POST("/servers/:id/connect", h.ConnectMCPServer)			mcp.DELETE("/servers/:id", h.DeleteMCPServer)			mcp.PUT("/servers/:id", h.UpdateMCPServer)			mcp.GET("/servers/:id", h.GetMCPServer)			mcp.GET("/servers", h.ListMCPServers)			mcp.POST("/servers", h.CreateMCPServer)		{		mcp := v1.Group("/mcp")		// MCP routes		}			llm.GET("/models", h.ListModels)			llm.DELETE("/configs/:id", h.DeleteLLMConfig)			llm.PUT("/configs/:id", h.UpdateLLMConfig)			llm.GET("/configs/:id", h.GetLLMConfig)			llm.GET("/configs", h.ListLLMConfigs)			llm.POST("/configs", h.CreateLLMConfig)		{		llm := v1.Group("/llm")		// LLM config routes		}			chat.POST("/stream", h.StreamMessage)			chat.POST("/send", h.SendMessage)		{		chat := v1.Group("/chat")		// Chat routes (for real-time messaging)		}			agents.GET("", h.ListAgents)			agents.DELETE("/:id", h.DeleteAgent)			agents.PUT("/:id", h.UpdateAgent)			agents.GET("/:id", h.GetAgent)			agents.POST("", h.CreateAgent)		{		agents := v1.Group("/agents")		// Agent routes		}			sessions.GET("/:id/messages", h.GetSessionMessages)			sessions.DELETE("/:id", h.DeleteSession)			sessions.PUT("/:id", h.UpdateSession)			sessions.GET("/:id", h.GetSession)			sessions.POST("", h.CreateSession)		{		sessions := v1.Group("/sessions")		// Session routes		}			users.GET("/:id/agents", h.GetUserAgents)			users.GET("/:id/sessions", h.GetUserSessions)			users.PUT("/:id", h.UpdateUser)			users.GET("/:id", h.GetUser)		{		users := v1.Group("/users")		// User routes		}			auth.POST("/refresh", h.RefreshToken)			auth.POST("/logout", h.Logout)			auth.POST("/login", h.Login)		{		auth := v1.Group("/auth")		// Auth routes	{	v1 := router.Group("/api/v1")	// API v1	router.GET("/ready", h.Ready)	router.GET("/health", h.Health)	// Health checkfunc RegisterRoutes(router *gin.Engine, h *handler.Handler) {// RegisterRoutes registers all HTTP routes.}	logger.Info("Server stopped")	}		logger.Error("Server forced to shutdown", log.Error(err))	if err := server.Shutdown(ctx); err != nil {	defer cancel()	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)	// Graceful shutdown	logger.Info("Shutting down server...")	<-quit	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)	quit := make(chan os.Signal, 1)	// Wait for shutdown signal	}()		}			logger.Fatal("HTTP server failed", log.Error(err))		if err := server.ListenAndServe(); err != nil && err != http.ErrServerClosed {		logger.Info("HTTP server started", log.String("addr", cfg.GetHTTPAddr()))	go func() {	// Start server in goroutine	}		IdleTimeout:  cfg.HTTP.IdleTimeout,		WriteTimeout: cfg.HTTP.WriteTimeout,		ReadTimeout:  cfg.HTTP.ReadTimeout,		Handler:      router,		Addr:         cfg.GetHTTPAddr(),	server := &http.Server{	// Create HTTP server	RegisterRoutes(router, h)	// Register routes	h := handler.NewHandler(logger)	// Initialize handlers	}		router.Use(middleware.CORS(cfg.HTTP.CORSOrigins))	if cfg.HTTP.EnableCORS {	router.Use(middleware.Recovery(logger))	router.Use(middleware.Logger(logger))	router.Use(middleware.RequestID())	// Add middlewares	router := gin.New()	}		gin.SetMode(gin.ReleaseMode)	if cfg.IsProd() {	// Setup Gin	}		logger.Fatal("Failed to init snowflake", log.Error(err))	if err := snowflake.Init(2); err != nil {	// Initialize snowflake ID generator	)		log.String("version", cfg.Service.Version),		log.String("name", cfg.Service.Name),	logger.Info("Starting ChateeHTTP service",	logger := log.Default()	}		os.Exit(1)		fmt.Fprintf(os.Stderr, "Failed to init logger: %v\n", err)	}); err != nil {		AddCaller: true,		Format:    cfg.Log.Format,		Level:     cfg.Log.Level,	if err := log.Init(log.LogConfig{	// Initialize logger	}		os.Exit(1)		fmt.Fprintf(os.Stderr, "Failed to load config: %v\n", err)	if err != nil {	cfg, err := config.Load("")	// Load configurationfunc main() {)	"chatee/services/chatee-http/middleware"	"chatee/services/chatee-http/handler"	"chatee/commonlib/snowflake"	"chatee/commonlib/log"	"chatee/commonlib/config"	"github.com/gin-gonic/gin"	"time"	"syscall"	"os/signal"	"os"	"net/http"	"fmt"