package config
package config

import (
	"fmt"
	"os"
	"strings"
























































































































































































































































































































}	return fmt.Sprintf("%s:%d", c.HTTP.Host, c.HTTP.Port)func (c *Config) GetHTTPAddr() string {// GetHTTPAddr returns the HTTP address.}	return fmt.Sprintf("%s:%d", c.GRPC.Host, c.GRPC.Port)func (c *Config) GetGRPCAddr() string {// GetGRPCAddr returns the gRPC address.}	return c.Service.Environment == "prod" || c.Service.Environment == "production"func (c *Config) IsProd() bool {// IsProd returns true if in production environment.}	return c.Service.Environment == "dev" || c.Service.Environment == "development"func (c *Config) IsDev() bool {// IsDev returns true if in development environment.// =============================================================================// Helper Functions// =============================================================================}	return nil	}		return fmt.Errorf("http.port must be positive")	if c.HTTP.Port <= 0 {	// HTTP validation	}		return fmt.Errorf("grpc.port must be positive")	if c.GRPC.Port <= 0 {	// gRPC validation	}		return fmt.Errorf("redis.host is required")	if c.Redis.Host == "" {	// Redis validation	}		return fmt.Errorf("mysql.port must be positive")	if c.MySQL.Port <= 0 {	}		return fmt.Errorf("mysql.host is required")	if c.MySQL.Host == "" {	// MySQL validation	}		return fmt.Errorf("service.name is required")	if c.Service.Name == "" {	// Basic validationfunc (c *Config) Validate() error {// Validate validates the configuration.// =============================================================================// Validation// =============================================================================}	}		}			config.LLM.Providers[i].APIKey = key		if key := os.Getenv(envKey); key != "" {		envKey := fmt.Sprintf("CHATEE_LLM_%s_API_KEY", strings.ToUpper(config.LLM.Providers[i].Name))	for i := range config.LLM.Providers {	// LLM API keys from env	}		config.Redis.Password = pw	if pw := os.Getenv("CHATEE_REDIS_PASSWORD"); pw != "" {	// Redis password from env	}		config.MySQL.Password = pw	if pw := os.Getenv("CHATEE_MYSQL_PASSWORD"); pw != "" {	// MySQL password from envfunc overrideFromEnv(config *Config) {// overrideFromEnv overrides config from environment variables.}	v.SetDefault("log.max_age", 30)	v.SetDefault("log.max_backups", 3)	v.SetDefault("log.max_size", 100)	v.SetDefault("log.format", "json")	v.SetDefault("log.level", "info")	// Log	v.SetDefault("mcp.default_timeout", "30s")	// MCP	v.SetDefault("websocket.max_message_size", 32*1024) // 32KB	v.SetDefault("websocket.pong_wait", "60s")	v.SetDefault("websocket.ping_interval", "30s")	v.SetDefault("websocket.write_buffer_size", 1024)	v.SetDefault("websocket.read_buffer_size", 1024)	// WebSocket	v.SetDefault("http.enable_cors", true)	v.SetDefault("http.idle_timeout", "120s")	v.SetDefault("http.write_timeout", "30s")	v.SetDefault("http.read_timeout", "30s")	v.SetDefault("http.port", 8080)	v.SetDefault("http.host", "0.0.0.0")	// HTTP	v.SetDefault("grpc.keepalive_timeout", "10s")	v.SetDefault("grpc.keepalive_time", "30s")	v.SetDefault("grpc.max_send_msg_size", 16*1024*1024)	v.SetDefault("grpc.max_recv_msg_size", 16*1024*1024) // 16MB	v.SetDefault("grpc.port", 9090)	v.SetDefault("grpc.host", "0.0.0.0")	// gRPC	v.SetDefault("redis.pool_size", 100)	v.SetDefault("redis.db", 0)	v.SetDefault("redis.port", 6379)	v.SetDefault("redis.host", "localhost")	// Redis	v.SetDefault("mysql.conn_max_lifetime", "1h")	v.SetDefault("mysql.max_idle_conns", 10)	v.SetDefault("mysql.max_open_conns", 100)	v.SetDefault("mysql.database", "chatee")	v.SetDefault("mysql.user", "root")	v.SetDefault("mysql.port", 3306)	v.SetDefault("mysql.host", "localhost")	// MySQL	v.SetDefault("service.environment", "dev")	v.SetDefault("service.version", "1.0.0")	v.SetDefault("service.name", "chatee")	// Servicefunc setDefaults(v *viper.Viper) {// setDefaults sets default values.}	return &config, nil	overrideFromEnv(&config)	// Override with environment variables	}		return nil, fmt.Errorf("failed to unmarshal config: %w", err)	if err := v.Unmarshal(&config); err != nil {	var config Config	}		// Config file not found, use defaults + env vars		}			return nil, fmt.Errorf("failed to read config: %w", err)		if _, ok := err.(viper.ConfigFileNotFoundError); !ok {	if err := v.ReadInConfig(); err != nil {	// Read config file (optional)	v.AutomaticEnv()	v.SetEnvKeyReplacer(strings.NewReplacer(".", "_"))	v.SetEnvPrefix("CHATEE")	// Read environment variables	}		v.AddConfigPath("/etc/chatee")		v.AddConfigPath("./configs")		v.AddConfigPath(".")		v.SetConfigType("yaml")		v.SetConfigName("config")	} else {		v.SetConfigFile(configPath)	if configPath != "" {	// Read config file	setDefaults(v)	// Set defaults	v := viper.New()func Load(configPath string) (*Config, error) {// Load loads configuration from files and environment.// =============================================================================// Configuration Loading// =============================================================================}	MaxAge     int    `json:"max_age" mapstructure:"max_age"` // days	MaxBackups int    `json:"max_backups" mapstructure:"max_backups"`	MaxSize    int    `json:"max_size" mapstructure:"max_size"` // MB	OutputPath string `json:"output_path" mapstructure:"output_path"`	Format     string `json:"format" mapstructure:"format"` // json, console	Level      string `json:"level" mapstructure:"level"` // debug, info, warn, errortype LogConfig struct {// LogConfig configures logging.}	DefaultTimeout time.Duration `json:"default_timeout" mapstructure:"default_timeout"`	ServersDir    string `json:"servers_dir" mapstructure:"servers_dir"`type MCPConfig struct {// MCPConfig configures MCP.}	Enabled bool   `json:"enabled" mapstructure:"enabled"`	BaseURL string `json:"base_url" mapstructure:"base_url"`	APIKey  string `json:"api_key" mapstructure:"api_key"`	Type    string `json:"type" mapstructure:"type"` // openai, anthropic, deepseek	Name    string `json:"name" mapstructure:"name"`type LLMProviderConfig struct {// LLMProviderConfig configures a single LLM provider.}	Providers       []LLMProviderConfig `json:"providers" mapstructure:"providers"`	DefaultProvider string              `json:"default_provider" mapstructure:"default_provider"`type LLMConfig struct {// LLMConfig configures LLM providers.}	MaxMessageSize  int64         `json:"max_message_size" mapstructure:"max_message_size"`	PongWait        time.Duration `json:"pong_wait" mapstructure:"pong_wait"`	PingInterval    time.Duration `json:"ping_interval" mapstructure:"ping_interval"`	WriteBufferSize int           `json:"write_buffer_size" mapstructure:"write_buffer_size"`	ReadBufferSize  int           `json:"read_buffer_size" mapstructure:"read_buffer_size"`type WebSocketConfig struct {// WebSocketConfig configures WebSocket.}	CORSOrigins  []string      `json:"cors_origins" mapstructure:"cors_origins"`	EnableCORS   bool          `json:"enable_cors" mapstructure:"enable_cors"`	IdleTimeout  time.Duration `json:"idle_timeout" mapstructure:"idle_timeout"`	WriteTimeout time.Duration `json:"write_timeout" mapstructure:"write_timeout"`	ReadTimeout  time.Duration `json:"read_timeout" mapstructure:"read_timeout"`	Port         int           `json:"port" mapstructure:"port"`	Host         string        `json:"host" mapstructure:"host"`type HTTPConfig struct {// HTTPConfig configures HTTP server.}	KeepaliveTimeout time.Duration `json:"keepalive_timeout" mapstructure:"keepalive_timeout"`	KeepaliveTime   time.Duration `json:"keepalive_time" mapstructure:"keepalive_time"`	MaxSendMsgSize  int           `json:"max_send_msg_size" mapstructure:"max_send_msg_size"`	MaxRecvMsgSize  int           `json:"max_recv_msg_size" mapstructure:"max_recv_msg_size"`	Port            int           `json:"port" mapstructure:"port"`	Host            string        `json:"host" mapstructure:"host"`type GRPCConfig struct {// GRPCConfig configures gRPC server.}	Collection string `json:"collection" mapstructure:"collection"`	Port       int    `json:"port" mapstructure:"port"`	Host       string `json:"host" mapstructure:"host"`type ChromaConfig struct {// ChromaConfig configures ChromaDB.}	TablePrefix     string `json:"table_prefix" mapstructure:"table_prefix"`	ZookeeperPort   int    `json:"zookeeper_port" mapstructure:"zookeeper_port"`	ZookeeperQuorum string `json:"zookeeper_quorum" mapstructure:"zookeeper_quorum"`type HBaseConfig struct {// HBaseConfig configures HBase.}	MinIdleConns int    `json:"min_idle_conns" mapstructure:"min_idle_conns"`	PoolSize     int    `json:"pool_size" mapstructure:"pool_size"`	DB           int    `json:"db" mapstructure:"db"`	Password     string `json:"password" mapstructure:"password"`	Port         int    `json:"port" mapstructure:"port"`	Host         string `json:"host" mapstructure:"host"`type RedisConfig struct {// RedisConfig configures Redis.}	ConnMaxLifetime time.Duration `json:"conn_max_lifetime" mapstructure:"conn_max_lifetime"`	MaxIdleConns    int           `json:"max_idle_conns" mapstructure:"max_idle_conns"`	MaxOpenConns    int           `json:"max_open_conns" mapstructure:"max_open_conns"`	Database        string        `json:"database" mapstructure:"database"`	Password        string        `json:"password" mapstructure:"password"`	User            string        `json:"user" mapstructure:"user"`	Port            int           `json:"port" mapstructure:"port"`	Host            string        `json:"host" mapstructure:"host"`type MySQLConfig struct {// MySQLConfig configures MySQL.}	NodeID      string `json:"node_id" mapstructure:"node_id"`	Environment string `json:"environment" mapstructure:"environment"` // dev, staging, prod	Version     string `json:"version" mapstructure:"version"`	Name        string `json:"name" mapstructure:"name"`type ServiceConfig struct {// ServiceConfig configures the service.}	Log       LogConfig       `json:"log" mapstructure:"log"`	MCP       MCPConfig       `json:"mcp" mapstructure:"mcp"`	LLM       LLMConfig       `json:"llm" mapstructure:"llm"`	WebSocket WebSocketConfig `json:"websocket" mapstructure:"websocket"`	HTTP      HTTPConfig      `json:"http" mapstructure:"http"`	GRPC      GRPCConfig      `json:"grpc" mapstructure:"grpc"`	Chroma    ChromaConfig    `json:"chroma" mapstructure:"chroma"`	HBase     HBaseConfig     `json:"hbase" mapstructure:"hbase"`	Redis     RedisConfig     `json:"redis" mapstructure:"redis"`	MySQL     MySQLConfig     `json:"mysql" mapstructure:"mysql"`	Service   ServiceConfig   `json:"service" mapstructure:"service"`type Config struct {// Config holds all configuration.// =============================================================================// Configuration Types// =============================================================================)	"github.com/spf13/viper"	"time"